version: '2'
services:
    platformtrusted-app:
        image: platformtrusted
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://platformtrusted-mysql:3306/platformtrusted?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    platformtrusted-mysql:
        extends:
            file: mysql.yml
            service: platformtrusted-mysql
